version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: openform_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openform
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
