[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["nodejs", "go", "gcc", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.frontend-build]
cmds = ["npm run build"]
dependsOn = ["install"]

[phases.build]
cmds = ["go build -o app ./cmd/web"]
dependsOn = ["frontend-build"]

[start]
cmd = "./app"

[variables]
CGO_ENABLED = "1"
